spring.application.name=app
server.port=8080
# ===============================
# CONEXIÓN A LA BASE DE DATOS
# ===============================
# URL de conexión (Cambia 'foro_db' por el nombre exacto de tu base de datos en phpMyAdmin)
spring.datasource.url=jdbc:mysql://localhost:3306/foro_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

# Credenciales de acceso
spring.datasource.username=root
spring.datasource.password=

# Controlador de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===============================
# Le dice a Spring que estamos usando MySQL para que traduzca bien las consultas
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# ¡LA MAGIA DE JPA! 'update' crea las tablas automáticamente si no existen, y las actualiza si agregas columnas
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de VS Code las consultas SQL que Java hace por debajo (muy útil para ver cómo funciona)
spring.jpa.show-sql=true